### ISSUE TITLE
Some effects broken (Compare with N64 console)

### ISSUE THREAD

**Issue by jonaeru** [fgsfdsfgs/perfect_dark#26]
Sorry if this is known, but the following graphics were incomplete.
I tested this build. https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5879598251
Video: https://youtu.be/qtzlnEuvBY8

- CamSpy (Not enough distortion)
- Night Vision
- IR Scanner
- Menu Background
- Light
- Horizon Scanner
- Infiltration Intro cutscene
- Blur
- Highlight (Pickups, Players, Teams)
- Mauler (charge-up shot)
- Slayer (fly-by-wire rocket)

**Comment by fgsfdsfgs** [comment]
What do you mean by "Light"?
Currently any framebuffer effects like blur, menu backgrounds, cloaking and light halos don't work.

**Comment by ghost** [comment]
Light could mean either the lighting lens flares not working, or models being full bright.

**Comment by jonaeru** [comment]
> What do you mean by "Light"?

It mean light halos.

> Currently any framebuffer effects like blur, menu backgrounds, cloaking and light halos don't work.

I understood. Thank you.

**Comment by jonaeru** [comment]
I have checked that some of the graphics have been fixed. Thank you.
I tested this build. https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5987730156
Video: https://youtu.be/-6w_LLtTLf0

OK:
- Night Vision
- Menu Background
- Light Halo
- Highlight (Pickups, Players, Teams)
- Mauler (charge-up shot)

Not OK:

- CamSpy (The screen is fine, but not enough distortion)
- IR Scanner
- Horizon Scanner
- Infiltration Intro cutscene
- Blur
- Slayer (fly-by-wire rocket)

**Comment by jonaeru** [comment]
I have checked that some of the graphics have been fixed. Thank you.
I made a comparison with the N64 console.
Build: https://github.com/fgsfdsfgs/perfect_dark/actions/runs/6216037392 (31bb7c6)
Video: https://youtu.be/lB6ayFnRnVA


## List

OK:
- Menu Background
- Light Halo
- Rain
- Snow
- Infiltration intro
- Gas
- Cloaking
- Highlight (Pickups, Players, Teams)
- Night Vision
- X-Ray Scanner
- IR Scanner
- Mauler (charge-up shot)
- FarSight XR-20
- Slayer (fly-by-wire rocket)
- Screen Shake

Mostly OK (some problems):
- Sky (Sunlight penetrating)
- Slow Motion (Lots of footsteps are heard in Defense) https://youtu.be/lB6ayFnRnVA?t=1188
- CamSpy (The screen is fine, but not enough distortion)

Not OK:
- Blur
- Horizon Scanner
- Attack Ship Barrier
- Skedar Ruins Bridge
- Autogun (Investigation, Crash Site)


## Sky
Sunlight penetrating
### PC Port
![Sky(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/5299e786-0f0a-425c-96ce-bc40d24b308b)
### N64 Console
![Sky(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/92dbb5af-5132-4a17-8506-d6412e4fc687)


## CamSpy
The screen is fine, but not enough distortion
### PC Port
![CamSpy(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/55c3a01f-11c2-47fd-834c-342d95166c89)
### N64 Console
![CamSpy(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/ac0f25d0-c6ea-4a3c-9179-597fdf2a8a38)


## Attack Ship Barrier
### PC Port
![Attack_Ship_Barrier(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/15652f22-a23c-4897-beb4-ec735e28bbec)
### N64 Console
![Attack_Ship_Barrier(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/7baa7661-bfe0-487f-a73d-bdf9bf89a633)


## Skedar Ruins Bridge
### PC Port
![Skedar_Ruins_Bridge1(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/325319c7-410e-4db8-92a1-73505b7395cd)
![Skedar_Ruins_Bridge2(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/2e4e6de3-8176-4b3a-9977-99cf68b4b683)
### N64 Console
![Skedar_Ruins_Bridge1(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/15212948-1214-4fe7-827b-b151dfa53fab)
![Skedar_Ruins_Bridge2(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/7134c7e0-2f5f-401d-8ea6-f0c32d4f852c)


## Autogun (Investigation, Crash Site)
### PC Port
![Autogun(Investigation)(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/878e5373-a5f9-4055-a313-c4a74c2ea8f7)
![Autogun(CrashSite)(PC)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/c018f7d6-672d-4c45-997d-bcac219f8319)
### N64 Console
![Autogun(Investigation)(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/b7233e65-3876-461c-9645-2ab22336c302)
![Autogun(CrashSite)(N64)](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/9dd4c520-8908-4e4e-bc12-c1f957abd3fd)

**Comment by ghost** [comment]
The bridge isn't red anymore and turret colors are fixed. Though the textures are still kind of messed up, I wonder how the n64 handles texture mirroring. Maybe it's some kind of minor difference with fast3d vs whatever perfect dark is using

**Comment by fgsfdsfgs** [comment]
Mirroring is handled correctly for at least some textures. I am not sure why it isn't handled correctly in some cases.

**Comment by ghost** [comment]
Would something like gl_mirrored_repeat fix it or am I completely wrong? I think this is the crossbow texture

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/115612060/661a60ea-545b-4e24-a9a1-21e5c1bedb5d)

But yeah that still wouldn't explain why it happens either

**Comment by fgsfdsfgs** [comment]
No, what I mean is it is *supposed* to set `GL_MIRRORED_REPEAT` or `GL_MIRROR_CLAMP_TO_EDGE` there, but it doesn't for some reason.

**Comment by omega-tuna** [comment]
Yeah that's what i was trying to say, I was agreeing with you. Sorry about that

**Comment by fgsfdsfgs** [comment]
Motion blur, combat boost blur and fisheye effect on the eyespy should now be in. Some of the textures above were also fixed in a recent PR.

**Comment by jonaeru** [comment]
Thank you. I made a comparison with the N64 console.
Build: https://github.com/fgsfdsfgs/perfect_dark/actions/runs/6539395852 (1eb1e96)
Video: https://youtu.be/81JJ8mkjtjo


## List

OK:
- Menu Background
- Light Halo
- Rain
- Snow
- Infiltration intro
- Gas
- Motion Blur
- Cloaking
- Highlight (Pickups, Players, Teams)
- Night Vision
- X-Ray Scanner
- IR Scanner
- Mauler (charge-up shot)
- FarSight XR-20
- Slayer (fly-by-wire rocket)
- Screen Shake
- Autogun (Investigation, Crash Site)

Mostly OK (some problems):
- Sky (Sunlight penetrating)
- Slow Motion (Lots of footsteps are heard in Defense) https://youtu.be/81JJ8mkjtjo?t=1053s (17:33)
  Similar to this? https://github.com/fgsfdsfgs/perfect_dark/pull/53
- CamSpy (Ceiling disappears in Investigation) https://youtu.be/81JJ8mkjtjo?t=1608s (26:48)
- Skedar Ruins Bridge (Graphics are not correct)
  Similar to this? https://github.com/fgsfdsfgs/perfect_dark/issues/25

Not OK:
- Horizon Scanner
- Attack Ship Barrier

**Comment by fgsfdsfgs** [comment]
Thank you for the detailed report.
The bridge issue looks to be the result of a wrong alpha blending mode + some transparent surface sorting issues. Perhaps it's actually supposed to have depth buffering enabled but it doesn't, or something similar to that.
I have no clue why the ceiling disappears though. Maybe the camspy *almost* clips through it when you go all the way up, but due to floating point error it appears to the clipping code as if it *is* through it, so the ceiling stops rendering.

UPD: Horizon scanner effect is now implemented. Also fixed a bug that made you autoturn when you had it out.

**Comment by jonaeru** [comment]
Thank you. Horizon scanner effect seems fine.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/81c2e47a-9452-4986-b2f2-0f5487ce1e0e)

**Comment by pHANTOMpHREAK9P** [comment]
![Screenshot 2023-10-21 031140](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/ace9b8e4-e51f-4749-a4fc-fb4c6a395961)
![Screenshot 2023-10-21 031035](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/623434ac-f0d6-4bff-a020-5fb498f88efa)
![Screenshot 2023-10-21 031055](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/d2a3f12f-e284-4d6e-96ff-b3d0df8f2b42)

Certain textures (and some planes that are not visible textures in the vent corners) will appear as a blue texture during the CamSpy tutorial section in the Carrington Institute. This problem did not exist before the proper fish eye lens effect that was recently applied.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by pHANTOMpHREAK9P** [comment]
![Screenshot 2023-10-21 233529](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/8fdce434-da06-4ae9-89b8-02b456b7e7df)
![Screenshot 2023-10-21 233547](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/e39839b2-8763-45b4-bbff-98f85bd6c462)
![Screenshot 2023-10-21 233636](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/47753145-c7a8-4d13-984a-e64e86675531)
![Screenshot 2023-10-21 233943](https://github.com/fgsfdsfgs/perfect_dark/assets/148613878/bde7b0a2-6fc6-4296-87ac-9975b4b49ad8)

There are pink outlines on the edges of certain faces in the Carrington Institute.  Especially on hidden doors (the one in Daniel Carrington's office is also a misaligned texture).

**Comment by fgsfdsfgs** [comment]
Upon looking into this some more, the bullet hole thing isn't mirroring related. The full bullet hole texture actually has both halves in it:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/767f115c-63e9-4f91-95e5-3b474273159c)
This is in fact an issue with the renderer not handling texture LODs correctly.

**Comment by jonaeru** [comment]
Build: https://github.com/fgsfdsfgs/perfect_dark/actions/runs/7117212181 (aeb6851)

> Mostly OK (some problems):
> 
> * Sky (Sunlight penetrating)

Not fixed
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/fa6f0b15-c293-4771-b882-c4fa3bf20a27)


> * Slow Motion (Lots of footsteps are heard in Defense) https://youtu.be/81JJ8mkjtjo?t=1053s (17:33)
>   Similar to this? [Fix spamming footsteps for slow mode #53](https://github.com/fgsfdsfgs/perfect_dark/pull/53)

Not fixed


> * CamSpy (Ceiling disappears in Investigation) https://youtu.be/81JJ8mkjtjo?t=1608s (26:48)

Probably OK
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/b9e09bd6-6104-479d-94e8-d67a78b541b4)

> * Skedar Ruins Bridge (Graphics are not correct)
>   Similar to this? [Datadyne: Defection Carpet Texture Broken #25](https://github.com/fgsfdsfgs/perfect_dark/issues/25)

OK
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/e1138c89-e3a9-4568-b62a-bb56781b0d5c)
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/9b3b829d-6b03-4fe0-aff5-0532bdca5688)

> Not OK:
> 
> * Horizon Scanner

OK
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/a7d152ce-53d6-48da-a332-6019d1b98598)

> * Attack Ship Barrier

OK
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/cd882f37-acfb-4110-bc03-a7cfeca37286)

**Comment by fgsfdsfgs** [comment]
The light glares have been improved somewhat in 15c0327. They're still not 100% accurate to N64.

**Comment by AluminumHaste** [comment]
Light glares seem insane right now, even on latest autobuild.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/734c8b64-e6fb-4bfc-bb7a-df29a38b8b17" />

First mission rescuing the doctor, really can't see anything at all.

**Comment by fgsfdsfgs** [comment]
What platform and ROM region?

**Comment by AluminumHaste** [comment]
Oh sorry about that.
Linux Build - Latest Auto Build from last month, downloaded today.
GPU: Radeon 7900XTX - Latest Mesa
CPU: Ryzen 5800X3D
Ubuntu 25.10
North America I guess would be the ROM I'm using
